name: Deployment to AWS EBS Sandbox environment

# Allow manual deployment trigger to AWS EBS Production environment available on GitHub if test workflow passes.
# The will only be from the following branches, because we are deploying to a sandbox environment.
# develop
# feature/*
# bugfix/*
on:
  workflow_dispatch --ref develop feature/* bugfix/*:
    workflows: ["test"]
      types:
        - completed

jobs:
  deploy:
    # Specify the operating system to run on
    runs-on: ubuntu-latest
    steps:
      # Check out to the code
      - name: Checkout Latest Repo
        uses: actions/checkout@master
        
      # Package all of the code into a zip file, except the node_modules folder.
      - name: Generate Deployment Package 
        run: zip -r deploy.zip * -x "**node_modules**"

      # Generate a formated current timestamp to use as the version label in this case.
      - name: Get timestamp
        uses: gerred/actions/current-time@master
        id: current-time

      - name: Run string replace
        uses: frabert/replace-string-action@master
        id: format-time
        with:
          pattern: '[:\.]+'
          string: "${{ steps.current-time.outputs.time }}"
          replace-with: '-'
          flags: 'g'

      # Push the zip file which contains the docker-compose file over to AWS Elastic Beanstalk.
      - name: Deploy to AWS EBS
        uses: einaregilsson/beanstalk-deploy@v14
        with:
          aws_access_key: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws_secret_key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          application_name: carsearch
          environment_name: carsearch-production
          version_label: "carsearch-deployment-${{ steps.format-time.outputs.replaced }}"
          region: ap-southeast-2
          deployment_package: deploy.zip
