name: Deployment From Github To AWS

# Only trigger, when the build workflow succeeded
on:
  workflow_dispatch:
    workflows: ["CI test"]
    types:
      - completed

jobs:
  deploy:
    # Run the latest version of Ubuntu.
    runs-on: ubuntu-latest
    steps:
      # Check out the code
      - name: Checkout Latest Repo
        uses: actions/checkout@master
        
      # Package all of the code into a zip file, except the node_modules folder.
      - name: Generate Deployment Package 
        run: zip -r deploy.zip * -x "**node_modules**"

      # Retrieve a formatted current timestamp, to use as the version label.
      - name: Get timestamp
        uses: gerred/actions/current-time@master
        id: current-time

      - name: Run string replace
        uses: frabert/replace-string-action@master
        id: format-time
        with:
          pattern: '[:\.]+'
          string: "${{ steps.current-time.outputs.time }}"
          replace-with: '-'
          flags: 'g'

      # Push the zip file which contains the docker-compose file over to AWS Elastic Beanstalk.
      - name: Deploy to EB
        uses: einaregilsson/beanstalk-deploy@v14
        with:
          aws_access_key: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws_secret_key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          application_name: carsearch
          environment_name: Carsearch-env
          version_label: "the-carsearch-deployment-${{ steps.format-time.outputs.replaced }}"
          region: ap-southeast-2
          deployment_package: deploy.zip
