name: Main

on:
  push:
    branches:
      - development
      - production

jobs:
  test:
    # Run the latest version of Ubuntu.
    runs-on: ubuntu-latest

    steps:
      # Check out the code.
      - uses: actions/checkout@v3

      # Use the same Node version we are using on our AWS EBS environments to serve our Docker image.
      - name: Use Node.js 12.x
        uses: actions/setup-node@v3
        with:
          node-version: 12.x

      # Install dependencies (clean install)
      - run: npm ci
      # Run unit tests
      - run: npm test

  set_environment_variables:
    runs-on: ubuntu-latest
    steps:
      - name: Set env var (development)
        if: github.ref == 'refs/heads/development'
          env:
            ENVIRONMENT: development

      - name: Set env var (production)
        if: github.ref == 'refs/heads/production'
          env:
            ENVIRONMENT: production

  deploy:
    uses: warahi-spenceley/carsearch/.github/workflows/deploy.yml@${{env.ENVIRONMENT}}
    with:
      environment_name: ${{env.ENVIRONMENT}}     